bin/jenkins/push2deis.sh

Jenkins script for the pushing to deis.

Jenkins push2deis script.

---

.gitignore
docs/gulp.rst
docs/index.rst
gulpfile.js
package.json

Removed un-needed stylus entry.
@craigcook very basic, I figure we can flush out the tasks & docs once there are more files.

Initial Gulp File Including Compilation For Stylus

---

masterfirefoxos/base/context_processors.py

Import settings as django_settings.

---

gulpfile.js
package.json

I started from a clean branch to make the commit on this much nicer.
This includes craig's new home task and the single colon task naming convention.
@craigcook please test locally and let me know if you run into any issues.

Added Gulp Sourcemaps

---

gulpfile.js

@craigcook bare bones watch task.. but it works.

Added gulp watch task.

---

masterfirefoxos/base/tests/test_views.py
masterfirefoxos/base/views.py
masterfirefoxos/settings/base.py
masterfirefoxos/urls.py

Redirect home to latest version slug for lang

---

masterfirefoxos/base/middleware.py
masterfirefoxos/base/static/js/main.js
masterfirefoxos/base/templates/includes/version-language-switcher.html
masterfirefoxos/base/tests/test_middleware.py

@glogiotatidis and/or @craigcook r?

Language version switch

---

masterfirefoxos/base/models.py
masterfirefoxos/base/tests/test_utils.py

Localize youtube_id

---

Dockerfile

Remove unnecessary deps and apt-get upgrade

---

masterfirefoxos/base/admin.py
masterfirefoxos/base/helpers.py
masterfirefoxos/base/migrate/medialibrary/0002_auto_20150128_1239.py
masterfirefoxos/base/migrate/page/0007_auto_20150128_1239.py
masterfirefoxos/base/migrate/page/0008_remove_quizquestion_image.py
masterfirefoxos/base/migrate/page/0009_quizquestion_image.py
masterfirefoxos/base/models.py
masterfirefoxos/base/templates/includes/imageparagraph.html
masterfirefoxos/base/tests/__init__.py
masterfirefoxos/base/tests/test_helpers.py
masterfirefoxos/base/tests/test_models.py
masterfirefoxos/base/tests/test_utils.py
masterfirefoxos/settings/base.py

Based of #55. Let's merge that first.

Localize images.

---

masterfirefoxos/base/models.py
masterfirefoxos/base/templates/includes/videoparagraph.html
masterfirefoxos/base/tests/test_utils.py
masterfirefoxos/base/utils.py

Add conditional youtube subtitle support

---

masterfirefoxos/base/models.py
masterfirefoxos/base/templates/home.html

Add homepage content region: fix bug 1128710

---

masterfirefoxos/base/models.py

Ideally I want to move the custom label code into a special admin widget if possible. I'll do a widget research on how to make TinyMCE on demand and maybe I figure out a way to fix this too. 
Meanwhile to unblock this, here's a quick fix.

 [fix bug 1129162] Respect blank value of model field. 

---

masterfirefoxos/base/admin.py
masterfirefoxos/base/templates/base.html
masterfirefoxos/base/templates/home.html

Add in_navigation to admin list_editable and list_display

Respect active and in_navigation: fix bug 1128819

---

masterfirefoxos/base/templates/includes/quizanswer.html
masterfirefoxos/base/templates/includes/quizquestion.html

Mark quiz fields as safe

---

masterfirefoxos/base/templates/includes/nav-information.html

Contact page de-scoped for launch per Natalia.

Removed Contact From Top Nav

---

bin/jenkins/makemessages.sh

Deis run cannot handle large output. Gzip db_strings before transfering
it over the wire.

Gzip db_strings output.

---

masterfirefoxos/base/static/js/ga.js
masterfirefoxos/base/templates/base.html
masterfirefoxos/settings/base.py

I think i got it.. it only took a few weeks.
I made this a sep js call, as it should go in the head.

Fix Bug 1126864: Add GA The Right Way

---

bin/run-common.sh
masterfirefoxos/base/__init__.py
masterfirefoxos/base/admin.py
masterfirefoxos/base/app.py
masterfirefoxos/base/migrations/0001_initial.py
masterfirefoxos/base/migrations/0002_auto_20150218_1128.py
masterfirefoxos/base/models.py
scripts/create_db_locales.py

This is the db part only. The plan is to merge this first, then create on dev and prod the locale / version mappings and then merge the second part switches from settings.py to the database.

Create database backend for locale / version mapping.

---

masterfirefoxos/base/templates/home.html

 [fix bug 1135114] Localize child.title. 

---

masterfirefoxos/settings/base.py

Fix video mix up

---

masterfirefoxos/base/middleware.py
masterfirefoxos/base/tests/test_middleware.py

override settings for ENABLE_ALL_LANGUAGES in tests

Remove authenticated user bypass of middleware

---

bin/jenkins/makemessages.sh
scripts/makemessages_all_locales.py

Call makemessages for all locales added to settings.LANGUAGES
Call new script from bin/jenkins/mamekessages.sh

Add makemessages_all_locales script

---

masterfirefoxos/settings/base.py

Fix Bug 1145737: Enable 2.0 Japanese

---

masterfirefoxos/settings/base.py

@jgmize or @glogiotatidis please review

Fix Bug 1149296: Enable ES 1.1, 1.3, 2.0

---

masterfirefoxos/settings/base.py

Fix Bug 1149742: Enable 2.0 For af, xh, zu

---

masterfirefoxos/settings/base.py

@jgmize r?
Minor but still want to check.

Fix Bug 1163786: Enable Tamil 1.3T

---

masterfirefoxos/settings/base.py

Fix Bug 1169007: Add ES 2.0 Videos

---

masterfirefoxos/settings/base.py

Fix Bug 1171622: Add ES 1.3 Videos

---

masterfirefoxos/settings/base.py

@jgmize minor. Would like to get this in today so I can update the screenshots for this locale prior to whistler.

Fix Bug 1175799: Enablel SW 2.0

---

masterfirefoxos/settings/base.py

@jgmize please review. Note my local install is still borked but I think this is correct.
Note the empty "locales"

Fix Bug 1194788: Enable 2.1: EN + ES

---

masterfirefoxos/settings/base.py

@jgmize just a settings change to enable bn-bd for 1.4

Fix Bug 1200000: Enable BN-BD 1.4

---

masterfirefoxos/settings/base.py

Enabling 1.1 & 1.3, note 1.3 was never pending but the translations are in.

Fix Bug 1213911: Enable Czech 1.1 & 1.3
